# Numpy Illustrated Guided
***this study guide follows: https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d***

In [239]:
import numpy as np
import random
import math

In [2]:
np.__version__

'1.19.2'

`Numpy` is inspired by `PyTorch`. 
<br>The ways in which arrays are different from lists:
- arrays handle one type of element (numbers) faster
- lists append faster
- arrays are more compact

In [3]:
l = [1,2,3]
[q*2 for q in l]

[2, 4, 6]

In [4]:
a = np.array([1,2,3])
a * 2

array([2, 4, 6])

In [5]:
la = [1,2,3]
lb = [4,5,6]
[q+r for q,r in zip(la,lb)]

[5, 7, 9]

In [6]:
aa = np.array([1,2,3])
ab = np.array([4,5,6])
aa + ab

array([5, 7, 9])

O(N) means the time necessary to complete the operation is proportional to the size of the array.
<br> O(1) **"amortized"** means that time does not generally depend on the size of the array
<br> This is a reference sheet for Big-O Complexities: https://www.bigocheatsheet.com/
<br> This is about Time Complexities in Python: https://wiki.python.org/moin/TimeComplexity

# Vectors, the 1D Arrays

In [7]:
v = np.array([1,2,3])

You should either grow a python list before committing it to numpy array or create an array with the necessary space with:

In [8]:
z = np.zeros(3, int)
z

array([0, 0, 0])

In [9]:
e = np.empty(3,int)
e

array([ 1152921504606846976, -9223363266511832552,                    2])

In [10]:
# This is going to match the shape of the input "a" variable
zl = np.zeros_like(a)
zl

array([0, 0, 0])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros_like(a)

array([0, 0, 0])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones_like(a)

array([1, 1, 1])

In [15]:
np.empty(3)

array([1., 1., 1.])

In [16]:
np.empty_like(a)

array([4607182418800017408, 4607182418800017408, 4607182418800017408])

In [18]:
np.full(3,7.)

array([7., 7., 7.])

In [20]:
np.full_like(a,7)

array([7, 7, 7])

The `_like` suffix simply compies the shape of another existing array/list

There are two functions for array initialization with monotonic sequences:
<br>`np.arange(start,stop,step)`
<br>`np.linspace(start,stop,num)`
<br> 


In [21]:
np.arange(6) #(stop)

array([0, 1, 2, 3, 4, 5])

In [22]:
np.arange(2,6) #(start,stop)

array([2, 3, 4, 5])

In [23]:
np.arange(1,6,2) #(start,stop,step)

array([1, 3, 5])

In [28]:
np.arange(3).astype(float)

array([0., 1., 2.])

In [29]:
np.arange(3.)

array([0., 1., 2.])

In [31]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [27]:
np.linspace(0, 0.5, 6)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])

`arange` is not optimal for handling floats, it is better with integers
<br>***The `0.1` in `step` is read by the computer as an infinite decimal that is rounded which is how is oversteps the `stop` point.***
<br> Solution: use `linspace`

In [32]:
np.arange(0.4, 0.8, 0.1)

array([0.4, 0.5, 0.6, 0.7])

In [33]:
np.arange(0.5, 0.8, 0.1) #This gives irregular result. It should stop before 0.8

array([0.5, 0.6, 0.7, 0.8])

In [34]:
np.arange(0.5, 0.75, 0.1) #Solution

array([0.5, 0.6, 0.7])

In [36]:
np.linspace(0.5, 0.7, 3) # Solution with linspace

array([0.5, 0.6, 0.7])

In [43]:
np.linspace(0,1,11) # you want 10 intevals for 0.1,0.2.... so you should use 10+1 in linspace

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

The point to watch with linspace is that you want the `number + 1` of intervals you are imagining.

In [101]:
np.random.randint(0,10) #The np random generator does not include 10

9

In [108]:
random.randint(0,10)    #The random generator does

10

In [44]:
np.random.randint(0,10,3)

array([6, 3, 0])

In [126]:
np.random.rand(3)

array([0.89369957, 0.35221707, 0.07104639])

In [127]:
np.random.randn(3) # includes negatives

array([ 0.40416237,  0.57677821, -0.20399451])

In [128]:
np.random.uniform(1,10,3)

array([5.46452302, 6.35143783, 8.64163716])

In [129]:
np.random.normal(5,2,3) 

array([8.16967213, 4.26003418, 6.63861323])

***Vector Indexing***

In [132]:
vi = np.arange(1,6)
vi

array([1, 2, 3, 4, 5])

In [133]:
vi[1] 

2

In [134]:
vi[2:4]

array([3, 4])

In [135]:
vi[-2:]

array([4, 5])

In [136]:
vi[::2]

array([1, 3, 5])

In [137]:
vi[[1,3,4]]   #Fancy Indexing

array([2, 4, 5])

In [139]:
vi[2:4] = 0
vi

array([1, 2, 0, 0, 5])

**All the indexing except `fancy indexing` are views**

In [144]:
# Python List
ca = [1,2,3]
cb = ca         # no copy
cc = ca[:]      # copy
cd = ca.copy()  # copy

In [147]:
# Numpy Array
cna = np.array([1,2,3])
cnb = cna        # no copy
cnc = cna[:]     # no copy!!!
cnd = cna.copy() # copy

**Appending**

In [141]:
lst = [1,2,3]
lst[1:2] = [5,6]  # This does work because it is a list
lst

[1, 5, 6, 3]

In [140]:
vi[1:2] = [5,6]  # This does not work because it is a numpy array
vi

ValueError: cannot copy sequence with size 2 to array axis with dimension 1

use `np.insert` or `np.append` explained later in `2D` 

**boolean indexing** can change the values though...

In [148]:
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])

In [149]:
np.any(a > 5)

True

In [150]:
np.all(a > 5)

False

In [151]:
a[a > 5]

array([6, 7, 6])

In [152]:
a[a > 5] = 0

In [153]:
a

array([1, 2, 3, 4, 5, 0, 0, 0, 5, 4, 3, 2, 1])

In [154]:
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])

In [155]:
a[(a >= 3) & (a <= 5)] = 0

In [156]:
a

array([1, 2, 0, 0, 0, 6, 7, 6, 0, 0, 0, 2, 1])

`ternary` comparisons like `3<=a<=5`

In [157]:
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])

In [158]:
np.where(a>5)

(array([5, 6, 7]),)

In [159]:
np.nonzero(a>5)

(array([5, 6, 7]),)

---------

In [161]:
a[a < 5] = 0 #This changes the variable

In [162]:
a[a >= 5] = 1 #This changes the variable

In [163]:
a

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [168]:
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])

In [169]:
np.where(a >=5, 1,0) #This does not change the variable

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [167]:
a

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

-----------

In [170]:
a[a < 3] = 3

In [171]:
a[a > 5] = 5

In [172]:
a

array([3, 3, 3, 4, 5, 5, 5, 5, 5, 4, 3, 3, 3])

In [173]:
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])

In [174]:
np.clip(a,3,5)   # This is not inplace

array([3, 3, 3, 4, 5, 5, 5, 5, 5, 4, 3, 3, 3])

In [175]:
a

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [176]:
np.clip(a,3,5,out=a)  # This is inplace

array([3, 3, 3, 4, 5, 5, 5, 5, 5, 4, 3, 3, 3])

In [177]:
a

array([3, 3, 3, 4, 5, 5, 5, 5, 5, 4, 3, 3, 3])

---------

Numpy is built on C++ so there is no tax from the slower python loops

In [186]:
one = np.array([1,2])
two = np.array([4,8])
three = np.array([2,5])
four = np.array([3,4])
five = np.array([2,3])

In [181]:
one + two

array([ 5, 10])

In [182]:
one - two

array([-3, -6])

In [183]:
two * three

array([ 8, 40])

In [184]:
two / three

array([2. , 1.6])

In [185]:
two // three

array([2, 1])

In [187]:
four ** five

array([ 9, 64])

Scalars can be promoted (`broadcasted`) to arrays

In [190]:
one * 3

array([3, 6])

In [189]:
one - 3

array([-2, -1])

In [191]:
one * 3

array([3, 6])

In [192]:
one / 3

array([0.33333333, 0.66666667])

In [193]:
one // 2

array([0, 1])

In [194]:
four ** 2

array([ 9, 16])

There are numpy methods that do that same as python operators

In [197]:
sq_five = five ** 2
sq_five

array([4, 9])

In [199]:
np.sqrt(sq_five)

array([2., 3.])

In [200]:
np.exp([1,2])

array([2.71828183, 7.3890561 ])

In [201]:
np.log([np.e, np.e**2])

array([1., 2.])

$\overrightarrow{a} · \overrightarrow{b}$ 

In [202]:
np.dot([1,2],[3,4])

11

$\overrightarrow{a} * \overrightarrow{b}$

In [204]:
np.cross([2,0,0],[0,3,0])

array([0, 0, 6])

In [209]:
np.sin([(np.pi),(np.pi/2)])   ### DONT KNOW WHAT THE MISTAKE IS BUT SHOULD BE [0.,1.]

array([1.2246468e-16, 1.0000000e+00])

In [206]:
np.arcsin([0.,1.])

array([0.        , 1.57079633])

In [208]:
np.hypot([3.,5.], [4.,12.])

array([ 5., 13.])

In [210]:
np.floor([1.1,1.5,1.9,2.5])

array([1., 1., 1., 2.])

In [211]:
np.ceil([1.1,1.5,1.9,2.5])

array([2., 2., 2., 3.])

In [212]:
np.round([1.1,1.5,1.9,2.5])

array([1., 2., 2., 2.])

In [215]:
arr = [1,2,3]

In [216]:
np.max(arr)

3

In [221]:
np.argmax(arr)

2

In [219]:
np.min(arr)

1

In [222]:
np.argmin(arr)

0

In [223]:
np.sum(arr)

6

In [224]:
np.var(arr)

0.6666666666666666

In [225]:
np.mean(arr)

2.0

In [226]:
np.std(arr)

0.816496580927726

In [228]:
arr.sort()

In [229]:
arr

[1, 2, 3]

**Python Lists:** `a.index(x[,i[,j]])` occurance of x between indices i and j

In [231]:
a.sort()   # inplace Python list
sorted(a)  # returns new sorted array

[3, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 5]

**Numpy Arrays:** `np.where(a==x)[0][0]` finds all the occurances first(not elegant or fast)
- `next(i[0] for i,v in np.ndenumerate(a) if v==x)` needs numba 
- `np.searchsorted(a,x)` needs sorted array
     

In [232]:
a.sort()   #inplace numpy array
np.sort(a) # returns new sorted array

array([3, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 5])

**Numba** https://numba.pydata.org/

In [234]:
np.where

<function numpy.where>

In [240]:
print(0.1 + 0.2 == 0.3)   # What!! This is False?
print(np.allclose(0.1 + 0.2, 0.3))
print(math.isclose(0.1 + 0.2, 0.3))

False
True
True


In [243]:
print(1e-9 == 2e-9)
print(np.allclose(1e-9, 2e-9))  # What!! This is True?
print(math.isclose(1e-9, 2e-9))

False
True
False


In [246]:
print(0.1 + 0.2 - 0.3 == 0)
print(np.allclose(0.1 + 0.2 - 0.3, 0))
print(math.isclose(0.1 + 0.2 - 0.3, 0))

False
True
False


`np.allclose` assumes all the numbers to be compared to be of a typical scale of 1
<br>needs `np.allclose(1e-9, 2e-9, atol=1e-17)==False`



`math.isclose` makes no assumptions about the numbers to be compared
<br>needs `math.isclose(0.1+0.2-0.3, abs_tol=1e-8)==True`
