In [1]:
import numpy as np
import random
import math

# 3D Arrays

# $a_{ijk}$

In [2]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
a = np.array([[[0,0,0,0],
           [0,0,0,0]],
          [[1,1,1,1],
           [1,1,1,1]],
          [[2,2,2,2],
           [2,2,2,2]]])

In [8]:
a.shape==(3,2,4)  #(z,y,x) or (i,j,k) or (/,v,>)

True

In [9]:
a

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2]]])

In [11]:
a.ndim == 3  # There are 3 dimensions

True

In [13]:
b = np.array([ [[0,1,2], [0,1,2], [0,1,2], [0,1,2]],
           [[0,1,2], [0,1,2], [0,1,2], [0,1,2]] ])
b

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [14]:
b.shape == (2,4,3)

True

In [17]:
a

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2]]])

# $im_{ijk}$

In [22]:
im = np.dstack((a))
im

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [23]:
im.shape==(2,4,3) #(y,x,z) or (i,j,k) or (v,>,/)

True

**`a[i,j]` gives an `(r,g,b)` tuple of the `(i,j)` pixel**

In [24]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [26]:
np.zeros((4,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
a = np.arange(1,25).reshape(3,4,2)
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])