# Numpy Illustrated Guide - 2D Arrays

In [1]:
import numpy as np
import random
import math

In [2]:
two_d= np.array([[1,2,3],[4,5,6]])

In [3]:
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
two_d.dtype 

dtype('int64')

In [5]:
two_d.shape

(2, 3)

In [6]:
len(two_d)

2

In [8]:
two_d.shape[0]

2

In [9]:
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.full((3,2),7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [13]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Double paranthesis are necessary because the second positional parameter is reserveed for the (optional) dtype (which also accepts integers).

In [17]:
np.random.randint(0,10,[3,2])

array([[1, 7],
       [5, 2],
       [3, 3]])

In [18]:
np.random.rand(3,2)

array([[0.58523258, 0.7192607 ],
       [0.43307105, 0.22786146],
       [0.94449657, 0.08955012]])

In [19]:
np.random.randn(3,2)

array([[ 0.66447169,  0.3548224 ],
       [ 1.02730731,  0.73763008],
       [-0.39053523,  1.76572023]])

In [20]:
np.random.uniform(1,10,[3,2])

array([[6.97051014, 6.59270047],
       [9.09268799, 4.22801129],
       [6.97465253, 3.25579014]])

In [21]:
np.random.normal(10,2,[3,2])

array([[ 9.96995533, 10.95300753],
       [ 9.27104627, 10.87534385],
       [11.73354756,  6.81045957]])

In [35]:
a = np.arange(1,13).reshape(3,4)

In [36]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
a[1,2]  # View

7

In [38]:
a[1,:]  # View

array([5, 6, 7, 8])

In [39]:
a[:,2]  # View

array([ 3,  7, 11])

In [40]:
a[:,1:3]  # View

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [41]:
a[-2:,-2:]  # View

array([[ 7,  8],
       [11, 12]])

In [42]:
a[::2,1::2]  # View

array([[ 2,  4],
       [10, 12]])

`axis = 0` is the column
<br>`axis = 1` is the row
<br> `axis` is also known as `dimension` 

In [45]:
a = np.arange(1,7).reshape(2,3)

In [46]:
a

array([[1, 2, 3],
       [4, 5, 6]])

$\displaystyle\sum_{ij} a_{ij}$
<br>i = axis[0]
<br>j = axis[1]

In [47]:
a.sum()

21

$\displaystyle\sum_i a_{ij}$

In [53]:
a.sum(axis=0) 
# for any given column, sum over all of its rows, or the sum of each column


array([5, 7, 9])

$\displaystyle\sum_j a_{ij}$

In [52]:
a.sum(axis=1)  # sum all the numbers in each row 

array([ 6, 15])

***Einstein Summation***

In [56]:
np.einsum('ij->j',a) == a.sum(axis=0) 

array([ True,  True,  True])

In [57]:
np.einsum('ij->i',a) == a.sum(axis=1)

array([ True,  True])

***Matrix arithmetic***

In [58]:
a = np.arange(1,5).reshape(2,2)

In [59]:
a

array([[1, 2],
       [3, 4]])

In [60]:
e = np.eye(2, dtype=int)

In [61]:
e

array([[1, 0],
       [0, 1]])

In [62]:
a+e

array([[2, 2],
       [3, 5]])

In [63]:
a-e

array([[0, 2],
       [3, 3]])

In [64]:
f = np.array([[2,0],[0,2]])

In [65]:
f

array([[2, 0],
       [0, 2]])

In [66]:
g = np.array([[2,1],[1,2]])

In [67]:
g

array([[2, 1],
       [1, 2]])

In [68]:
a*f

array([[2, 0],
       [0, 8]])

In [70]:
# This is the matrix product
a@f

array([[2, 4],
       [6, 8]])

In [71]:
a/g

array([[0.5, 2. ],
       [3. , 2. ]])

In [72]:
a**g

array([[ 1,  2],
       [ 3, 16]])

In [73]:
a3x3= np.arange(1,10).reshape(3,3)

In [74]:
a3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
# Normailzation
a3x3/9

array([[0.11111111, 0.22222222, 0.33333333],
       [0.44444444, 0.55555556, 0.66666667],
       [0.77777778, 0.88888889, 1.        ]])

In [77]:
# Multiply several columns at once
a3x3 * np.array([-1,0,1])

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [78]:
# Row-wise Normalization
a3x3 / np.array([[3],[6],[9]])

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [80]:
# Outer Product
a3x3[0] * np.array([[1],[2],[3]])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [85]:
# Outer Product
np.array([[1],[2],[3]]) @ np.array([[1,2,3]])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [84]:
# Dot Product
np.array([[1,2,3]])@np.array([[1],[2],[3]])

array([[14]])

------

**.T**

In [86]:
a = np.arange(1,7).reshape(2,3)

In [87]:
a

array([[1, 2, 3],
       [4, 5, 6]])

$a_{ij} \rightarrow a_{ji}$

In [88]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
b = np.array([[1,2,3]]).reshape(1,3)

In [93]:
b.T

array([[1],
       [2],
       [3]])

In [94]:
c = np.array([[1,2,3]]).reshape(3,)

In [96]:
c.T

array([1, 2, 3])

------
**Reshaping and Indexing with `newaxis`**

In [97]:
a = np.arange(1,7).reshape(6,)

In [98]:
a

array([1, 2, 3, 4, 5, 6])

In [99]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [100]:
a[None,:]

array([[1, 2, 3, 4, 5, 6]])

In [101]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [104]:
a[:,None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

The -1 aregument tells the `reshape` to calculate on of the dimension sizes automatically and `None` in square brackets serve as a shortcut for `np.newaxis` which adds an empty axis at the designated place.

The types of vectors:
- 1D arrays
- 2D row vectors
- 2D column vectors

**1D Vector**

In [106]:
a = np.array([1,2,3])

**2D Row Vector** THIS IS NOT NECESSARY DUE TO `BROADCASTING`

In [111]:
r = a[None,:]
r

array([[1, 2, 3]])

In [110]:
r = a[np.newaxis, :]
r

array([[1, 2, 3]])

In [112]:
r = a.reshape(1,-1)
r

array([[1, 2, 3]])

**2D Column Vector**

In [113]:
c = a.reshape(-1,1)
c

array([[1],
       [2],
       [3]])

In [115]:
c = a[:, np.newaxis]
c

array([[1],
       [2],
       [3]])

In [116]:
c = a[:,None]
c

array([[1],
       [2],
       [3]])

**2D Vector $\rightarrow$ 1D Vector**

In [117]:
r.flatten()

array([1, 2, 3])

In [118]:
r.reshape(-1)

array([1, 2, 3])

In [119]:
np.ravel(r)

array([1, 2, 3])

In [120]:
c.flatten()

array([1, 2, 3])

In [121]:
c.reshape(-1)

array([1, 2, 3])

In [122]:
np.ravel(c)

array([1, 2, 3])

**2D Vector Row $\leftrightarrow$ 2D vector Column**

In [123]:
r.T

array([[1],
       [2],
       [3]])

In [124]:
c.T

array([[1, 2, 3]])

**Matrix manipulations**
<br>**Stacking**
<br>**2D and 2D**

In [127]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
b = np.arange(1,9).reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
c = np.arange(1,7).reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
np.hstack((a,c))

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [134]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

**2D and 1D** 
<br> hstack generates and error

In [135]:
b = np.array([1,2,3,4]).reshape(4,)
c = np.array([1,3,5]).reshape(3,)

In [138]:
c

array([1, 3, 5])

In [139]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [141]:
np.hstack((a,c[:,None]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [142]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [143]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

**Splitting**

In [145]:
b = np.arange(1,9).reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [146]:
c = np.arange(1,7).reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [149]:
y = np.hstack((a,c))
y

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [152]:
d = np.hsplit(y,[4])
d

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[1, 2],
        [3, 4],
        [5, 6]])]

In [153]:
x = np.vstack((a,b))
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [154]:
e = np.vsplit(x,[3])
e

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]])]

**Replicate Matrix**

In [156]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [157]:
np.tile(a,(2,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [158]:
b = a.repeat(3,axis=1)
b

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [160]:
b.repeat(2,axis=0)

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4],
       [3, 3, 3, 4, 4, 4]])

In [164]:
a =  np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

**Delete columns/rows**

In [172]:
h = np.delete(a,[1,3], axis = 1) # Eliminates the columns indexed at 1 and 3
h

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [177]:
v = np.delete(a, 1, axis=0)  # Eliminates the row at index 1
v

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [179]:
u = np.delete(a, np.s_[1:-1], axis= 1)
u

array([[ 1,  5],
       [ 6, 10],
       [11, 15]])

In [181]:
np.delete(a, slice(1,-1), axis=1)

array([[ 1,  5],
       [ 6, 10],
       [11, 15]])

In [184]:
w = np.delete(a,[0,-1], axis=1)
w

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

**Insert**

In [174]:
np.insert(h, [1,2], 0, axis =1)  # We see that the insert happens to the left of the indices named

array([[ 1,  0,  3,  0,  5],
       [ 6,  0,  8,  0, 10],
       [11,  0, 13,  0, 15]])

In [178]:
np.insert(v,1,7,axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 7,  7,  7,  7,  7],
       [11, 12, 13, 14, 15]])

In [185]:
np.insert(u,[1],w,axis=1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

**Append** functions like `hstack` or `column_stack`

In [196]:
np.append(a, np.zeros((3,2)), axis=1)

array([[ 1.,  2.,  3.,  4.,  5.,  0.,  0.],
       [ 6.,  7.,  8.,  9., 10.,  0.,  0.],
       [11., 12., 13., 14., 15.,  0.,  0.]])

In [197]:
np.column_stack((a, np.zeros(3)))

array([[ 1.,  2.,  3.,  4.,  5.,  0.],
       [ 6.,  7.,  8.,  9., 10.,  0.],
       [11., 12., 13., 14., 15.,  0.]])

In [205]:
np.append(a, np.ones((1,5)), axis=0)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [ 1.,  1.,  1.,  1.,  1.]])

**Pad** a little complicated

In [209]:
np.pad(a,((0,0),(2,2)))

array([[ 0,  0,  1,  2,  3,  4,  5,  0,  0],
       [ 0,  0,  6,  7,  8,  9, 10,  0,  0],
       [ 0,  0, 11, 12, 13, 14, 15,  0,  0]])

In [212]:
np.pad(a,((0,1),(0,2)), constant_values=3)

array([[ 1,  2,  3,  4,  5,  3,  3],
       [ 6,  7,  8,  9, 10,  3,  3],
       [11, 12, 13, 14, 15,  3,  3],
       [ 3,  3,  3,  3,  3,  3,  3]])

In [208]:
np.pad(a,1)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  9, 10,  0],
       [ 0, 11, 12, 13, 14, 15,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

**Meshgrids**

**The Python Way**

In [225]:
c = [[(j-i) for j in range(5)] for i in range(3)]
c

[[0, 1, 2, 3, 4], [-1, 0, 1, 2, 3], [-2, -1, 0, 1, 2]]

In [226]:
c = [[(j-i) for j in range(3)] for i in range(2)]
c

[[0, 1, 2], [-1, 0, 1]]

In [227]:
a = np.array(c)
a

array([[ 0,  1,  2],
       [-1,  0,  1]])

**The Numpy Way**

In [230]:
i,j = np.arange(2), np.arange(3)

In [231]:
i

array([0, 1])

In [232]:
j

array([0, 1, 2])

In [233]:
I,J = np.meshgrid(i,j,sparse=True, indexing='ij')

In [234]:
I

array([[0],
       [1]])

In [235]:
J

array([[0, 1, 2]])

In [236]:
I,J = np.ogrid[:2,:3]

In [237]:
I

array([[0],
       [1]])

In [238]:
J

array([[0, 1, 2]])

In [239]:
I,J = np.indices((2,3), sparse=True)

In [240]:
I

array([[0],
       [1]])

In [241]:
J

array([[0, 1, 2]])

In [242]:
J-I

array([[ 0,  1,  2],
       [-1,  0,  1]])

**Matrix Statistics**

In [243]:
a = np.array([[4,8,5],[9,3,1]])

In [244]:
a

array([[4, 8, 5],
       [9, 3, 1]])

$m = \displaystyle\min_{i,j} a_{ij}$
<br>`a.min()=1`

$m_{j} = \displaystyle\min_{i} a_{ij}$  
<br>`a.min(axis=0) = array([4, 3, 1])`

$m_{i} = \displaystyle\min_{j} a_{ij}$
<br> `a.min(axis=1) = array([4, 1])`

$ k = arg\   \displaystyle\min_{i,j}\ a_{ij} $
<br> `a.argmin() = 5`

In [255]:
np.unravel_index(a.argmin(), a.shape)==(1,2)

True

$z_{j}= arg\   \displaystyle\min_{i}\ a_{ij}$ 
<br> `a.argmin(axis=0) = array([0, 1, 1])`

$z_{i} =arg\ \displaystyle\min_{j}\ a_{ij}$
<br> `a.argmin(axis=1) = array([0, 2])`

In [259]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [260]:
np.any(a>5)

True

In [261]:
np.any(a>5, axis=0)

array([False, False,  True])

In [262]:
np.any(a>5, axis=1)

array([False,  True])

**Matrix Sorting**

In [263]:
a = np.array([[4,8,5],[9,3,1]])

In [265]:
a.sort(axis=0)

In [266]:
a

array([[4, 3, 1],
       [9, 8, 5]])

In [267]:
a = np.array([[4,8,5],[9,3,1]])

In [268]:
a.sort(axis=1)

In [269]:
a

array([[4, 5, 8],
       [1, 3, 9]])

In [270]:
a[a[:,0].argsort()]

array([[1, 3, 9],
       [4, 5, 8]])

In [277]:
a = np.array([[7,4,6,5]])

In [278]:
np.sort(a)

array([[4, 5, 6, 7]])

In [279]:
np.argsort(a)

array([[1, 3, 2, 0]])

In [281]:
b = np.array([[7,2,9],[4,3,8,],[6,1,7],[5,0,4]]) 
b

array([[7, 2, 9],
       [4, 3, 8],
       [6, 1, 7],
       [5, 0, 4]])

In [282]:
b[[1,3,2,0]]

array([[4, 3, 8],
       [5, 0, 4],
       [6, 1, 7],
       [7, 2, 9]])

In [291]:
a[np.argsort(a[:,0])]

array([[7, 4, 6, 5]])

In [292]:
a[np.argsort(a[:,1])]

array([[7, 4, 6, 5]])

In [293]:
b[np.argsort(b[:,0], kind='stable')]

array([[4, 3, 8],
       [5, 0, 4],
       [6, 1, 7],
       [7, 2, 9]])

In [299]:
a = np.array([[3,4],[2,7],[1,5],[2,6]])
a

array([[3, 4],
       [2, 7],
       [1, 5],
       [2, 6]])

In [298]:
a[np.argsort(a[:,0])]

array([[1, 5],
       [2, 7],
       [2, 6],
       [3, 4]])

In [302]:
b = a[np.argsort(a[:,1])]
b

array([[3, 4],
       [1, 5],
       [2, 6],
       [2, 7]])

In [304]:
b[np.argsort(b[:,0], kind='stable')]

array([[1, 5],
       [2, 6],
       [2, 7],
       [3, 4]])

**`lexsort`**

In [308]:
b = np.rot90(a)
b

array([[4, 7, 5, 6],
       [3, 2, 1, 2]])

In [309]:
c = np.lexsort(b)
c

array([2, 3, 1, 0])

In [310]:
a[c]

array([[1, 5],
       [2, 6],
       [2, 7],
       [3, 4]])